/**
 * Builds the videos page into one file to paste into an Elementor HTML widget.
 *
 *   node build-videos.mjs
 *
 * Output: elementor/videos-page.html
 *
 * Kept separate from build.mjs because the two pages share nothing at
 * runtime — they never appear together, so a shared bundle would only make
 * both of them bigger.
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const src = (n) => readFile(join(root, "src", n), "utf8");

const [markup, css, js] = await Promise.all([
  src("videos-markup.html"),
  src("videos.css"),
  src("videos.js"),
]);

const safe = (s) => s.replace(/<\/script>/gi, "<\\/script>");

const out = `<!--
  ================================================================
  Talitha Kum Kenya - Videos page
  Generated by build-videos.mjs - do not edit this file directly.
  Edit the files in src/ and run: node build-videos.mjs

  HOW TO INSTALL
  1. In WordPress, create a Category called "Videos" (slug: videos).
  2. Edit the Videos page in Elementor.
  3. Drop in an "HTML" widget, full width, no padding.
  4. Paste this entire file into it, then Update.

  Nothing is uploaded on this page - a video is just a link. No YouTube or
  Vimeo code loads until a visitor presses play.
  ================================================================
-->

<style>
${css.trim()}
</style>

${markup.trim()}

<script>
${safe(js).trim()}
</script>
`;

await mkdir(join(root, "elementor"), { recursive: true });
await writeFile(join(root, "elementor", "videos-page.html"), out, "utf8");

const kb = (s) => `${(Buffer.byteLength(s, "utf8") / 1024).toFixed(1)} KB`;
console.log(`built elementor/videos-page.html  ${kb(out)}`);
console.log(`  css ${kb(css)}   markup ${kb(markup)}   js ${kb(js)}`);
