/**
 * Builds each rebuilt site page into one file to paste into Elementor.
 *
 *   node build-site.mjs
 *
 * Output: elementor/site/<page>.html — chrome (header + footer) around the
 * page's own sections, with the shared CSS and JS inlined. Every file is
 * self-contained, so pages can be replaced one at a time.
 *
 * Each page should use the "Elementor Canvas" template (blank), because it
 * carries its own header and footer.
 */

import { readFile, writeFile, mkdir, readdir } from "node:fs/promises";
import { dirname, join, basename } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const S = (n) => readFile(join(root, "src", "site", n), "utf8");

const [css, js, head, foot] = await Promise.all([
  S("site.css"), S("site.js"), S("chrome-head.html"), S("chrome-foot.html"),
]);

const safe = (s) => s.replace(/<\/script>/gi, "<\\/script>");
const kb = (s) => `${(Buffer.byteLength(s, "utf8") / 1024).toFixed(1)} KB`;

const TITLES = {
  home: "Homepage",
  about: "About us",
  vision: "Vision, Mission & Values",
  contacts: "Contacts",
  donate: "Donate",
};

await mkdir(join(root, "elementor", "site"), { recursive: true });

const pages = (await readdir(join(root, "src", "site", "pages"))).filter((f) => f.endsWith(".html"));
for (const f of pages) {
  const name = basename(f, ".html");
  const content = await S(join("pages", f));
  const out = `<!--
  ================================================================
  Talitha Kum Kenya - ${TITLES[name] || name} (site rebuild)
  Generated by build-site.mjs - edit src/site/ and rebuild.

  HOW TO INSTALL
  1. Edit the page in Elementor.
  2. Page Settings (gear icon, bottom left) > Page Layout >
     "Elementor Canvas". This page carries its own header and
     footer, so the theme's must not also render.
  3. Drop in an "HTML" widget, full width, no padding.
  4. Paste this entire file into it, then Update.
  ================================================================
-->

<style>
${css.trim()}
</style>

<div class="tks">
${head.trim()}

${content.trim()}

${foot.trim()}
</div>

<script>
${safe(js).trim()}
</script>
`;
  await writeFile(join(root, "elementor", "site", `${name}.html`), out, "utf8");
  console.log(`built elementor/site/${name}.html  ${kb(out)}`);
}
