/**
 * Builds the team page into one file to paste into an Elementor HTML widget.
 *
 *   node build-team.mjs
 *
 * Output: elementor/team-page.html
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const src = (n) => readFile(join(root, "src", n), "utf8");

const [markup, css, js] = await Promise.all([
  src("team-markup.html"),
  src("team.css"),
  src("team.js"),
]);

const safe = (s) => s.replace(/<\/script>/gi, "<\\/script>");

const out = `<!--
  ================================================================
  Talitha Kum Kenya - Team page
  Generated by build-team.mjs - do not edit this file directly.
  Edit the files in src/ and run: node build-team.mjs

  HOW TO INSTALL
  1. In WordPress, create a Category called "Team" (slug: team).
  2. Edit the Team page in Elementor.
  3. Drop in an "HTML" widget, full width, no padding.
  4. Paste this entire file into it, then Update.

  Groups (Board, Staff) are created for you the first time you publish
  someone into them. Photographs go into the ordinary media library.
  ================================================================
-->

<style>
${css.trim()}
</style>

${markup.trim()}

<script>
${safe(js).trim()}
</script>
`;

await mkdir(join(root, "elementor"), { recursive: true });
await writeFile(join(root, "elementor", "team-page.html"), out, "utf8");

const kb = (s) => `${(Buffer.byteLength(s, "utf8") / 1024).toFixed(1)} KB`;
console.log(`built elementor/team-page.html  ${kb(out)}`);
console.log(`  css ${kb(css)}   markup ${kb(markup)}   js ${kb(js)}`);
