/**
 * Builds the single-paste Elementor block from the files in src/.
 *
 *   node build.mjs
 *
 * Output: elementor/publications-page.html
 *
 * Everything in src/ is the source of truth. Never hand-edit the built file —
 * it is overwritten on every build.
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const src = (name) => readFile(join(root, "src", name), "utf8");

const [markup, css, publicJs, adminJs] = await Promise.all([
  src("markup.html"),
  src("publications.css"),
  src("publications.js"),
  src("admin.js"),
]);

/* A </script> sequence anywhere inside the JS would close the tag early. */
const safe = (js) => js.replace(/<\/script>/gi, "<\\/script>");

const banner = `<!--
  ================================================================
  Talitha Kum RAHT Kenya - Publications repository
  Generated by build.mjs - do not edit this file directly.
  Edit the files in src/ and run: node build.mjs

  HOW TO INSTALL
  1. Edit the page in Elementor.
  2. Drop in an "HTML" widget, full width, no padding.
  3. Paste this entire file into it.
  4. Update, then view the page.

  Before it will show anything, create a Category in WordPress called
  "Publications" (slug: publications). See docs/setup.md.
  ================================================================
-->`;

const out = `${banner}

<style>
${css.trim()}
</style>

${markup.trim()}

<script>
${safe(publicJs).trim()}
</script>

<script>
${safe(adminJs).trim()}
</script>
`;

await mkdir(join(root, "elementor"), { recursive: true });
await writeFile(join(root, "elementor", "publications-page.html"), out, "utf8");

const kb = (s) => `${(Buffer.byteLength(s, "utf8") / 1024).toFixed(1)} KB`;
console.log(`built elementor/publications-page.html  ${kb(out)}`);
console.log(`  css ${kb(css)}   markup ${kb(markup)}   js ${kb(publicJs + adminJs)}`);
